### ISSUE TITLE
DNS-01 based challenge

### ISSUE THREAD

**Issue by EugenMayer** [rawmind0/alpine-traefik#100]
Its about this merged PR https://github.com/kubernetes/charts/pull/1299

Seems like it has been release with 1.5.0

Docs: https://docs.traefik.io/configuration/acme/ .. see `[acme.dnsChallenge]`

I guess we would need to add those new values to the catalog:

1) `provider` (full list :https://docs.traefik.io/configuration/acme/#provider )
2) API_USER
3) API_TOKEN

I would limit the list of supported `providers` to the actual user/token authenticated, since otherwise this feature would become a lot more complicated, espcially in the catalog UI.

I understand, that providing those individual ENV vars is kind of a hazzle in the docker-compose.tpl - so what about creating a script which takes our general provider USER/TOKEN attribtues as ENV params and then exports the corresponding ENV vars in a big switch case and creates /.acme_env

Before starting `traefik` we source that env file `. /.acme_env && traefik` and thats about it.
This way we could keep out the logic out of the docker-compose.tpl and maybe we even find such a script already.

**Comment by EugenMayer** [comment]
Seems its already prepared

```
- TRAEFIK_ACME_ENABLE="false"							# Enable/disable traefik ACME feature. [acme](https://docs.traefik.io/configuration/acme/)
- TRAEFIK_ACME_CHALLENGE=""                             # Set http | dns to activate traefik acme challenge mode. 
- TRAEFIK_ACME_CHALLENGE_HTTP_ENTRYPOINT="http"         # Set traefik acme http challenge entrypoint. [acme http challenge](https://docs.traefik.io/configuration/acme/#acmehttpchallenge)
- TRAEFIK_ACME_CHALLENGE_DNS_PROVIDER=""                # Set traefik acme dns challenge provider. You need to manually add configuration env variables accordingly the dns provider you use. [acme dns provider](https://docs.traefik.io/configuration/acme/#provider)
- TRAEFIK_ACME_CHALLENGE_DNS_DELAY=""                # Set traefik acme dns challenge delayBeforeCheck. [acme dns challenge](https://docs.traefik.io/configuration/acme/#acmednschallenge)
- TRAEFIK_ACME_EMAIL="test@traefik.io"					# Default email
- TRAEFIK_ACME_ONHOSTRULE="true"						# ACME OnHostRule parameter
- TRAEFIK_ACME_CASERVER="https://acme-v01.api.letsencrypt.org/directory"						# ACME caServer parameter
```

**Comment by EugenMayer** [comment]
lets continue in the PR i guess

**Comment by TemaSM** [comment]
@rawmind0 Hi there!
How is it going with DNS-01 challenge for support wildcard domains?
There's a bunch of issues/PRs created about DNS-01:
https://github.com/rawmind0/alpine-traefik/issues/100
https://github.com/rawmind0/alpine-traefik/pull/104
https://github.com/rawmind0/alpine-traefik/pull/121
Referred from: https://github.com/rawmind0/rancher-traefik/issues/74
We really need it and waiting for. Thanks in advance!
