### ISSUE TITLE
Generate SSL self-signed key on the fly

### ISSUE THREAD

**Issue by EugenMayer** [rawmind0/alpine-traefik#102]
Its way to critical to have an exposed priv/cert staticly in the image, use a generation method.

we could use this script easily https://github.com/EugenMayer/consul-docker-stability-tests/blob/master/acls/bin/server_tls.sh

i use it for several images like openldap and others to generate self signed certs on the fly

**Comment by rawmind0** [comment]
By the moment, you could overwrite docker ssl key/cert with env variable `TRAEFIK_SSL_KEY` and `TRAEFIK_SSL_CERT`. But sure, may be a good alternative use key generator. :)
