### ISSUE TITLE
You killed 1 gazzilion kittes due to doing bash-templating

### ISSUE THREAD

**Issue by EugenMayer** [rawmind0/alpine-traefik#103]
And you added 2 gazzilions in addition, since i know you know go-lang and go-template :)

We really might want to migrate that, that will be the most critical part of the whole image, how flexible the template is and how to extend it.

**Comment by EugenMayer** [comment]
to be honest, out of motivation discussing that

**Comment by rawmind0** [comment]
Yeah, i code in go lang and go templating. You are right here, but i started in bash templating and didn't find time to migrate.
