### ISSUE TITLE
traefik.frontend.headers.customRequestHeaders - EOF error

### ISSUE THREAD

**Issue by mkoczorowski** [rawmind0/alpine-traefik#111]
If I add a label traefik.frontend.headers.customRequestHeaders=EXPR into the container traefik logs an error 
```
level=error msg="Near line 177 (last key parsed 'frontends.frontend-Host-domain.headers.customRequestHeaders.Authorization'): unexpected EOF"
```

Am I doing anything wrong ?

**Comment by rawmind0** [comment]
What traefik version?? May be your `traefik.frontend.headers.customRequestHeaders=EXPR` is not correct?? I was testing with traefik v1.6.x and v1.7.0-rcx and working fine.
