### ISSUE TITLE
traefik v1.7.0-rc4 is out

### ISSUE THREAD

**Issue by mkoczorowski** [rawmind0/alpine-traefik#117]
Hi there v1.7.0-rc4 is out now fixing important bug when requesting new certificates.

Is there a change to get rc4 build please ?

**Comment by rawmind0** [comment]
Updated and released...

**Comment by mkoczorowski** [comment]
@rawmind0 you closed the isue so quickly that I haven't had time to say Thank you.. so
Thank you :]
