### ISSUE TITLE
Catalog not updated

### ISSUE THREAD

**Issue by emcniece** [rawmind0/alpine-traefik#14]
I'm attempting to implement `v1.0.3-rancher1` on my Rancher `v1.2.0-pre4-rc4` node, but the catalog only offers versions `v1.0.0-beta555-rancher1` and `v1.0.1-rancher1`.

Is it possible to manually add this to Rancher (ie. pasting the rancher-compose.yml somewhere), or is it possible to update the catalog somehow?

**Comment by rawmind0** [comment]
Hi @emcniece ...

Meanwhile, community catalog would be updated, you could add my personal catalog to your rancher and test and use that last version of the packages.

https://github.com/rawmind0/service-catalog

Best regards....
