### ISSUE TITLE
Traefik won't start after update

### ISSUE THREAD

**Issue by MikaXII** [rawmind0/alpine-traefik#15]
Hello,
So after an update on my host traefik won't start anymore. If this log can help you to find a solution...

```
26/10/2016 20:32:28'traefik' start: /opt/traefik/bin/traefik-service.sh
26/10/2016 20:32:28Wed Oct 26 18:32:28 UTC 2016 - [ Generating traefik configuration... ]
26/10/2016 20:32:28Wed Oct 26 18:32:28 UTC 2016 - [ Redirecting traefik log... ]
26/10/2016 20:32:28Wed Oct 26 18:32:28 UTC 2016 - [ Redirecting traefik log... ]
26/10/2016 20:32:28Wed Oct 26 18:32:28 UTC 2016 - [ Starting traefik... ]
26/10/2016 20:32:28nohup: appending output to nohup.out
```

```
$ cat nohup.out
time="2016-10-26T18:33:59Z" level=fatal msg="Error opening fileopen /opt/traefik
/log/access.log: permission denied"
```

```
$ ls -l log/
total 0
lrwxrwxrwx    1 traefik  traefik         12 Oct 26 18:35 access.log -> /proc/1/f
d/1
lrwxrwxrwx    1 traefik  traefik         12 Oct 26 18:35 traefik.log -> /proc/1/
fd/1
```

Edit I use the latest version 1.0.3-rancher1

**Comment by rawmind0** [comment]
HI @MikaXII , thanks for the info....

It's so strange. I have that version working on my rancher system. From which version do you try update?? 

Could you try to remove your traefik stack and redeploy it?? But before, could you please, add these commands output??

```
ls -l /proc/1/fd/1
ps -ef
```
 Best regards...

**Comment by MikaXII** [comment]
Docker : 1.12.2
Ubuntu 16.04 LTS
I've no update rancher version since a few week. But it's stable image.
It's after a upgrade of docker-engine.

```
$ ls -l /proc/1/fd/1
l-wx------    1 traefik  traefik         64 Oct 28 17:41 /proc/1/fd/1 -> pipe:[2
805134]
```

```
PID   USER     TIME   COMMAND
    1 traefik    0:00 bash /opt/monit/bin/monit-start.sh
   11 traefik    0:00 /opt/monit/bin/monit -I
   21 traefik    0:00 /opt/tools/confd/bin/confd -interval 10 -confdir /opt/too
   85 traefik    0:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/ba
   92 traefik    0:00 /bin/bash
  117 traefik    0:00 ps -ef
```

**Comment by duck1123** [comment]
I am also seeing this same issue. Redeploying does not seem to fix it.

Docker: 1.12.2
Ubuntu 16.04 LTS
Image: rawmind/alpine-traefik:1.0.3-1

$ rancher exec 1i151735 ls -l /proc/1/fd/1
`lrwx------    1 traefik  traefik         64 Oct 29 02:05 /proc/1/fd/1 -> /4`

$ rancher exec 1i151735 ps -ef                                                                                                                                                         ```
PID   USER     TIME   COMMAND
    1 traefik    0:00 bash /opt/monit/bin/monit-start.sh
   10 traefik    0:00 /opt/monit/bin/monit -I
   20 traefik    0:00 /opt/tools/confd/bin/confd -interval 60 -confdir /opt/tools/confd/etc -backend rancher -prefix /2015-12-19
   73 traefik    0:00 bash
  178 traefik    0:00 ps -ef
```

The issue goes away when I switch back to 1.0.1-1

**Comment by duck1123** [comment]
Issue occurs between 1.0.2-5 and 1.0.2-6

**Comment by MikaXII** [comment]
I make a dirty fix for myself (suppress link traefik.log and access.log) and I've update traefik-service.sh to remove log function.
With this fix if I choose `TRAEFIK_HTTPS_ENABLE=true || only` that doesn't work because traefik.crt and .key have root owner with perms 600 so 'permission denied'.

**Comment by rawmind0** [comment]
Hi all....

Could you please test the new traefik v1.1.1?? You shouldn't suffer this kind of problems...

thanks...Best regards...

**Comment by MikaXII** [comment]
Another issue when https is enable :

```
time="2016-11-30T22:57:35Z" level=info msg="Traefik version v1.1.1 built on 2016
-11-29_03:39:12PM"
time="2016-11-30T22:57:35Z" level=info msg="Using TOML configuration file /opt/t
raefik/etc/traefik.toml"
time="2016-11-30T22:57:35Z" level=error msg="Error opening fileopen /opt/traefik
/log/access.log: permission denied"
time="2016-11-30T22:57:35Z" level=info msg="Preparing server https &{Network: Ad
dress::443 TLS:0xc42031ede0 Redirect:<nil> Auth:<nil> Compress:false}"
time="2016-11-30T22:57:35Z" level=error msg="Error creating TLS config open /opt
/traefik/certs/traefik.crt: permission denied"
time="2016-11-30T22:57:35Z" level=fatal msg="Error preparing server: open /opt/t
raefik/certs/traefik.crt: permission denied"
```

```
 ls -l certs/
total 8
-rw-------    1 root     root          1785 Nov 30 22:57 traefik.crt
-rw-------    1 root     root          1704 Nov 30 22:57 traefik.key
```

**Comment by rawmind0** [comment]
Hi @MikaXII ...

how are you starting the service?? Are you setting some volume, or anything different??

Service is launched as a traefik user (no privileged), and he is owner of /opt/traefik . It makes no sense for me, the permission denied in access.log and in traefik.crt and traefik.key files...

To help you, i need to reproduce your issue, but actually i can't.

Launched in differents rancher versions from v1.1.2 to v1.2.0-rc2, with different hosts, rancheros, ubuntu and centos, and with different docker version...
This is my full log, launching traefik from the rancher catalog, with https enabled....
```
01/12/2016 00:51:05 New Monit id: e64ff98a40ef3527fe27c3f4c9f522c5
01/12/2016 00:51:05 Stored in '/opt/traefik/.monit.id'
01/12/2016 00:51:05Starting Monit 5.20.0 daemon with http interface at [*]:2812
01/12/2016 00:51:05'traefik_traefik_1' Monit 5.20.0 started
01/12/2016 00:51:05'confd' process is not running
01/12/2016 00:51:05'confd' trying to restart
01/12/2016 00:51:05'confd' start: '/opt/tools/confd/bin/service-conf.sh start'
01/12/2016 00:51:06Wed Nov 30 23:51:06 UTC 2016 - [ Restarting traefik... ]
01/12/2016 00:51:06Wed Nov 30 23:51:06 UTC 2016 - [ Stoping traefik... ]
01/12/2016 00:51:06cat: can't open '/opt/traefik/traefik.pid': No such file or directory
01/12/2016 00:51:06kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
01/12/2016 00:51:06Wed Nov 30 23:51:06 UTC 2016 - [ Generating traefik configuration... ]
01/12/2016 00:51:06Wed Nov 30 23:51:06 UTC 2016 - [ Redirecting traefik log... ]
01/12/2016 00:51:06Wed Nov 30 23:51:06 UTC 2016 - [ Redirecting traefik log... ]
01/12/2016 00:51:06Wed Nov 30 23:51:06 UTC 2016 - [ Starting traefik... ]
01/12/2016 00:51:06nohup: appending output to nohup.out
01/12/2016 00:51:06time="2016-11-30T23:51:06Z" level=info msg="Traefik version v1.1.1 built on 2016-11-29_03:39:12PM" 
01/12/2016 00:51:06time="2016-11-30T23:51:06Z" level=info msg="Using TOML configuration file /opt/traefik/etc/traefik.toml" 
01/12/2016 00:51:06time="2016-11-30T23:51:06Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc4201bb7a0 Redirect:<nil> Auth:<nil> Compress:false}" 
01/12/2016 00:51:06time="2016-11-30T23:51:06Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> Compress:false}" 
01/12/2016 00:51:06time="2016-11-30T23:51:06Z" level=info msg="Starting provider *provider.File {\"Watch\":true,\"Filename\":\"/opt/traefik/etc/rules.toml\",\"Constraints\":null}" 
01/12/2016 00:51:06time="2016-11-30T23:51:06Z" level=info msg="Starting provider *main.WebProvider {\"Address\":\":8000\",\"CertFile\":\"\",\"KeyFile\":\"\",\"ReadOnly\":false,\"Auth\":null}" 
01/12/2016 00:51:06time="2016-11-30T23:51:06Z" level=info msg="Server configuration reloaded on :80" 
01/12/2016 00:51:06time="2016-11-30T23:51:06Z" level=info msg="Server configuration reloaded on :443" 
01/12/2016 00:51:06time="2016-11-30T23:51:06Z" level=info msg="Starting server on :443" 
01/12/2016 00:51:06time="2016-11-30T23:51:06Z" level=info msg="Starting server on :80" 
01/12/2016 00:51:06Reinitializing monit daemon
01/12/2016 00:51:06Awakened by the SIGHUP signal
01/12/2016 00:51:06Reinitializing Monit - Control file '/opt/monit/etc/monitrc'
01/12/2016 00:51:06'traefik_traefik_1' Monit reloaded
```

```
bash-4.3$ ls -l certs/
total 8
-rw-------    1 traefik  traefik       2021 Nov 30 23:51 traefik.crt
-rw-------    1 traefik  traefik       3243 Nov 30 23:51 traefik.key
```

```
bash-4.3$ ls -l log/
total 0
lrwxrwxrwx    1 traefik  traefik         12 Nov 30 23:51 access.log -> /proc/1/fd/1
lrwxrwxrwx    1 traefik  traefik         12 Nov 30 23:51 traefik.log -> /proc/1/fd/1
```

**Comment by MikaXII** [comment]
Hi rawmind,

I just update the container via rancher, the previous version to rancher-1.1.1.
I do a fresh install too.
But I haven't no problem with log anymore.

**Comment by MikaXII** [comment]
EDIT : I work with acme support.

**Comment by rawmind0** [comment]
Hi @MikaXII ...

It's so annoying due to i couldn't reproduce your issue. root owner of crt and key files, makes no sense for me, due to all processes are launched with traefik user, that should be the owner of /opt/traefik 

It seems clear that we are missing something. In order to help you, i need to reproduce that and see what it's happening.

**Comment by duck1123** [comment]
I can confirm that the latest version corrected my issue.

**Comment by MikaXII** [comment]
Hi @rawmind0,

Well I removed my stack, update my host, recreate traefik 's stack and that work...
But thanks for your work :) you can close this issue.

**Comment by rawmind0** [comment]
Thank you guys, for the feedback...

**Comment by leopku** [comment]
This issue is permission of mounted volume related.

It would happen when the container started with volume as `-v ${HOST PATH}/traefik.toml:/opt/traefik/etc/traefik.toml` or `-v ${HOST PATH}/traefik:/opt/traefik`.

A way to fix it, operate in docker host:
1. add a group with gid 10001 
2. add a user with uid 10001
3. change uid and gid of file `${HOST PATH}/traefik.toml` or  dir `${HOST PATH}/traefik` to `10001:10001`
4. run a new container with volume described as above

**Comment by rawmind0** [comment]
Hi @leopku ... Thanks for your comment...

the container was not thought initially to be run with host volumes mapped. Logic has implemented to autogenerate traefik.toml. You could control some config parameters with env variables. 

Traefik is launched with a non privileged user (uid 10001, gid 10001), then you would need what you've commented, if you want to map a host volume.  :)

Best regards....

**Comment by fabiorauber** [comment]
Folks,

I believe this is caused by CoreOS 1235.x SELinux policy, now being enabled for the docker daemon. Looks very similar to https://github.com/coreos/bugs/issues/1757#issuecomment-272397527

**Comment by nireak** [comment]
Hi @rawmind0,

I have a doubt...if the container is not thought to use host volumes mapped how can I reference the certificate files (pem) I have in the host and want to use for the https traefik port using ONLY config parameters?

I've tried to fill TRAEFIK_SSL_PATH, TRAEFIK_SSL_CRT_FILE, etc but the program tries to overwrite them instead of using them... :(

I image that I could make another image based on yours and COPY my pem files to it but I would like to use yours directly.

In fact, the ideal way IMHO would be that traefik itself would autogenerate a cert for itself to enable the https port in the admin web interface of traefik like it does with ACME to other backend services.

Perhaps I'm missing something very obvious but I've been trying a way to solve it for several hours.

Thank you

**Comment by rawmind0** [comment]
Hi @nireak ,

the container doesn't use host volumes. It doesn't copy key or cert files, to avoid host dependencies.

To use your ssl key and cert, you need to fill `TRAEFIK_SSL_KEY= # ssl key content` and `TRAEFIK_SSL_CRT= # ssl cert content` . The image will copy them into files inside container and use them. This is the way to use your own key and cert. 

Best regards...

**Comment by nireak** [comment]
Hi @rawmind0 
Thank you for your quick answer!

The "problem" is that I have created these certs using Let's encrypt and they only last for 3 months... :(

Could it be possible to use ACME to generate it like it does for backends? It would be great! :)

**Comment by rawmind0** [comment]
Sure, you could use ACME... Take a look at README.md file....

Env variables
```
...
- TRAEFIK_ACME_ENABLE="false"	# Enable/disable traefik ACME feature
- TRAEFIK_ACME_EMAIL="test@traefik.io"	# Default email
- TRAEFIK_ACME_ONDEMAND="true"	# ACME ondemand parameter
- TRAEFIK_ACME_ONHOSTRULE="true"	# ACME OnHostRule parameter
- TRAEFIK_ACME_CASERVER="https://acme-v01.api.letsencrypt.org/directory"	# ACME caServer parameter
...
```

**Comment by nireak** [comment]
Thanks it worked!!! :)
