### ISSUE TITLE
how to specify `Path:/api` in the rules.toml config

### ISSUE THREAD

**Issue by macneib** [rawmind0/alpine-traefik#16]
Hi just starting out with traefik `1.0.1-1`, and I'm also using rancher  `v1.1.4`.  I've been following rawmind0/alpine-traefik examples and articles, and I've been able to get `web-test.backend.example.com` to point at a service my back-end stack (in time will be my api) as well as `web-test.proxy-test.example.com` to point at a my service in my other webserver stack (in time to become a lightweight webserver serving a browser client app).

tl;dr; In short, I would like to specify `;Path:/api` in the rules.toml config

Here's what I've been able to get working.

```
[backends]

    [backends.web-test__backend]
        [backends.web-test__backend.circuitbreaker]
            expression = "NetworkErrorRatio() > 0.5"
        [backends.web-test__backend.LoadBalancer]
            method = "drr"
        [backends.web-test__backend.servers.backend_web-test_1]
            url = "http://10.42.167.56:8080"
            weight = 0

    [backends.web-test__proxy-test]
        [backends.web-test__proxy-test.circuitbreaker]
            expression = "NetworkErrorRatio() > 0.5"
        [backends.web-test__proxy-test.LoadBalancer]
            method = "drr"
        [backends.web-test__proxy-test.servers.proxy-test_web-test_1]
            url = "http://10.42.8.81:8080"
            weight = 0

[frontends]

    [frontends.web-test__backend]
        backend = "web-test__backend"
        passHostHeader = true
        [frontends.web-test__backend.routes.service]
        rule = "Host:web-test.backend.example.com"

    [frontends.web-test__proxy-test]
        backend = "web-test__proxy-test"
        passHostHeader = true
        [frontends.web-test__proxy-test.routes.service]
        rule = "Host:web-test.proxy-test.example.com"
```

Here's where I'm somewhat confused.  Currently our web client makes http reqs to an api @  `example.com/api`  and I was under the assumption that I would be able to edit the `rules.toml` to something like:

```
[frontends]

   [frontends.web-test__backend]
       backend = "web-test__backend"
       passHostHeader = true
       [frontends.web-test__backend.routes.service]
       rule = "Host:dev.example.com;Path:/api"

   [frontends.web-test__proxy-test]
       backend = "web-test__proxy-test"
       passHostHeader = true
       [frontends.web-test__proxy-test.routes.service]
       rule = "Host:dev.example.com;"
```

where `dev.example.com` will route to the client and `dev.example.com/api` is routes to the api.  When I set this config in traefik in rancher the container crashes.  Not sure what I'm missing here.  Any help is very much appreciated.

**Comment by macneib** [comment]
update:
I've been able to edit the rules.toml maunally  and see it work, however the changes are persisteted for more than 60 seconds as the rancher meta data rewrites the rule
```
rule = "Host:dev.example.com;Path:/test"
```
get automatically rewritten as 
```
rule = "Host:web-test.proxy-test.example.com"
```

**Comment by rawmind0** [comment]
Hi @macneib ...

thank you very much for use traefik in rancher and the feedback.

Yes, rancher-traefik reads rancher metadata and rewrites rules.toml every 60 seconds by default. It looks for services labels and writes rules.toml accordingly. 
By the moment, path filter label is not implemented, but it could be done easily. 

I take note of that and  i look for any time to implement it shortly. :)

Best regards....

**Comment by macneib** [comment]
Hi @rawmind0!
Thanks that would be awesome! I really appreciate your work on traefik and rancher.  I'm pretty excited to use it for a few projects.

I was going to write the path filter label tonight, however I'm not especially knowledgeable on how the template fits together.  I'll close the issue.

**Comment by rawmind0** [comment]
Hi @macneib ...

added path label to the last version of rancher-traefik.... 

You could try it by adding https://github.com/rawmind0/service-catalog catalog to your rancher server....

**Comment by macneib** [comment]
Already on the case.  Thank you very much!
