### ISSUE TITLE
traefik won't start in rancher version 1.2

### ISSUE THREAD

**Issue by samouds** [rawmind0/alpine-traefik#18]
Hello,

I tried to deploy traefik in rancher v 1.2 using the community template but it won't. here are the logs : 

> 09/12/2016 08:20:09 New Monit id: c1491aafd515c976cfd2287bfedcba5e
09/12/2016 08:20:09 Stored in '/opt/traefik/.monit.id'
09/12/2016 08:20:09Starting Monit 5.20.0 daemon with http interface at [*]:2812
09/12/2016 08:20:09'traefik-traefik-1' Monit 5.20.0 started
09/12/2016 08:20:09'confd' process is not running
09/12/2016 08:20:09'confd' trying to restart
09/12/2016 08:20:09'confd' start: '/opt/tools/confd/bin/service-conf.sh start'
09/12/2016 08:20:09Fri Dec 9 07:20:09 UTC 2016 - [ Restarting traefik... ]
09/12/2016 08:20:09Fri Dec 9 07:20:09 UTC 2016 - [ Stoping traefik... ]
09/12/2016 08:20:09cat: can't open '/opt/traefik/traefik.pid': No such file or directory
09/12/2016 08:20:09kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
09/12/2016 08:20:09Fri Dec 9 07:20:09 UTC 2016 - [ Generating traefik configuration... ]
09/12/2016 08:20:09Fri Dec 9 07:20:09 UTC 2016 - [ Redirecting traefik log... ]
09/12/2016 08:20:09Fri Dec 9 07:20:09 UTC 2016 - [ Redirecting traefik log... ]
09/12/2016 08:20:09Fri Dec 9 07:20:09 UTC 2016 - [ Starting traefik... ]
09/12/2016 08:20:09nohup: appending output to nohup.out
09/12/2016 08:20:09'traefik' process is not running
09/12/2016 08:20:09'traefik' trying to restart
09/12/2016 08:20:09'traefik' start: '/opt/traefik/bin/traefik-service.sh start'
09/12/2016 08:20:09Reinitializing monit daemon
09/12/2016 08:20:09Fri Dec 9 07:20:09 UTC 2016 - [ Generating traefik configuration... ]
09/12/2016 08:20:09Fri Dec 9 07:20:09 UTC 2016 - [ Redirecting traefik log... ]
09/12/2016 08:20:09Fri Dec 9 07:20:09 UTC 2016 - [ Redirecting traefik log... ]
09/12/2016 08:20:09Fri Dec 9 07:20:09 UTC 2016 - [ Starting traefik... ]
09/12/2016 08:20:09nohup: appending output to nohup.out

Any idea please ?

**Comment by samouds** [comment]
I get this error in nohup.out : 

**level=fatal msg="Error preparing server: open /opt/t
raefik/certs/traefik.crt: permission denied"**

**Comment by MikaXII** [comment]
Hello,

Same issue here https://github.com/rawmind0/alpine-traefik/issues/15#issuecomment-264024413

**Comment by fabiorauber** [comment]
@samouds, are you using CoreOS? Bumped into the same bug, and it seems it is caused by SELinux CoreOS 1235.x policy:

**Comment by rawmind0** [comment]
Please, reopen if the problem persist.
