### ISSUE TITLE
ACME/letsencrypt with Rancher Community Catalog traefik 

### ISSUE THREAD

**Issue by austinnichols101** [rawmind0/alpine-traefik#19]
I have been successful at accessing the dashboard on 8000 and my application on 80.  However, when I try to access using port 443,  the connection times out with a `ERR_CONNECTION_REFUSED` from chrome.

I have tried setting TRAEFIK_HTTPS_ENABLE = true, but the container hangs `Initalizing` with the following log output.  I suspect this switch only applies if you are providing your own cert.

Thanks!

FYI - the current version in the rancher catalog is `1.1.2`.

```
2/23/2016 1:38:48 PMtime="2016-12-23T18:38:48Z" level=error msg="Error creating TLS config tls: failed to find any PEM data in certificate input" 
12/23/2016 1:38:48 PMtime="2016-12-23T18:38:48Z" level=fatal msg="Error preparing server: tls: failed to find any PEM data in certificate input" 
12/23/2016 1:39:18 PM'traefik' failed to start (exit status 0) -- no output

```

**TRAEFIK CONFIG**
```
rawmind/alpine-traefik:1.1.2

8000 > 8000
80 > 80
443 > 443

CONF_INTERVAL = 10
TRAEFIK_ACME_EMAIL = <redacted>
TRAEFIK_ACME_ENABLE = true
TRAEFIK_ACME_ONDEMAND = true
TRAEFIK_ACME_ONHOSTRULE = true
TRAEFIK_HTTPS_ENABLE = false
TRAEFIK_HTTPS_PORT = 443
TRAEFIK_HTTP_PORT = 80
```

**CONTAINER LABELS**
```
traefik.port = 8000
traefik.path = /
traefik.enable = stack
traefik.domain = <redacted>
traefik.alias = 
traefik.acme = true
```

**Comment by rawmind0** [comment]
Hi @austinnichols101 ...

to be able that traefik listen in https port, you have to set TRAEFIK_HTTPS_ENABLE = true and paste the correct ssl key and ssl crt in the catalog form (If you let them empty, a default test key and crt are loaded). 

The error that you attach me, it seems very strange. What are you setting in ssl key and ssl crt fields??

**Comment by rawmind0** [comment]
I've try to reproduce your problem, trying to deploy traefik with https and acme enable. I've deployed pasting a test ssl key and ssl crt in the catalog form, and letting them empty, and it seems that both are working ok.

**Comment by austinnichols101** [comment]
ok - I will try that and see what happens.

**Comment by rawmind0** [comment]
Please, reopen if the problem persist.

**Comment by volatilemolotov12** [comment]
Hello, 

How am i supposed to use ACME if i have to add cert to rancher form?
