### ISSUE TITLE
rancher-traefik image uses alpine 3.4 with known issue on rancher metadata resolution

### ISSUE THREAD

**Issue by jmahowald** [rawmind0/alpine-traefik#22]
Hi, I am having the behavior described in https://github.com/rawmind0/alpine-traefik/issues/3
and in
https://github.com/rawmind0/rancher-traefik/issues/19

Specifically confd can't get rancher metadata because the container can't resolve rancher-metadata (though it can resolve http://rancher-metadata.rancher.internal) 

while those issues say that the problem isn't in rancher traefik but rather in alpine 3.4 I'd have to disagree since the rancher-traefik image in the official catalog uses alpine 3.4.  Since it also depends on your monit dockerfile to fix I'd also need to fork that repo as well.  Or to change confd.

**Comment by jmahowald** [comment]
Looking further into this, building the full chain I think will be fine.  The issue is just that the rancher-traefik -> alpine-traefik hasn't been updated to use your newer alpine monit which is alpine 3.5 based.   For now I'll clone the chain and build images.

**Comment by rawmind0** [comment]
Hi @jmahowald .... 

The issue that you comment, are closed and resolved. These issues were for different reasons. Confd should resolve and connect just ok to rancher-metadata, as it's referenced in both issues. 

Alpine-traefik and rancher-traefik are working well in so many environments. Whic version are you using?? What is the content of your confd log file /opt/tools/confd/log/confd.log?? Are your services labels ok??

**Comment by jmahowald** [comment]
Well those previous issues weren't specific about which version of alpine-traefik was being used.  But the latest in docker-hub is shipped with alpine 3.4

```
docker run -it --entrypoint /bin/ash --rm rawmind/alpine-traefik:1.1.2-1 -c 'cat /etc/apk/repositories'

http://dl-cdn.alpinelinux.org/alpine/v3.4/main
http://dl-cdn.alpinelinux.org/alpine/v3.4/community
```

**Comment by rawmind0** [comment]
Yep, i know. Almost all versions of alpine and rancher traefik are based on alpine 3.4 . Issues were specific about used alpine version, 3.4. look at the last comment, an others,...https://github.com/rawmind0/alpine-traefik/issues/3

None of these issues were by alpine dns resolv issue, due to confd was resolving and connecting ok with rancher-metadata. They were by services labels or other problems.

What is the content of your traefik confd log file /opt/tools/confd/log/confd.log?? Are your services labels ok??

**Comment by jmahowald** [comment]
```
bash-4.3$ cat  /opt/tools/confd/log/confd.log
2017-01-29T22:59:11Z traefik_traefik_1 /opt/tools/confd/bin/confd[19]: INFO Back
end set to rancher
2017-01-29T22:59:11Z traefik_traefik_1 /opt/tools/confd/bin/confd[19]: INFO Star
ting confd
2017-01-29T22:59:11Z traefik_traefik_1 /opt/tools/confd/bin/confd[19]: INFO Back
end nodes set to
2017-01-29T22:59:11Z traefik_traefik_1 /opt/tools/confd/bin/confd[19]: INFO Usin
g Rancher Metadata URL: http://rancher-metadata
bash-4.3$

```

**Comment by rawmind0** [comment]
In confd log file there isn't any error. It seems that is connecting well with rancher backend.

Have your service healthchecks defined and are working?? Healthchecks are mandatory, only healthy services would be added to traefik.

**Comment by jmahowald** [comment]
PBCK - I had label keys of the above, e.g. 
I had

traefik.enable=true

as a key, rather than key of `traefik.enable`.  Closing. Thanks for responding and for the work in the first place
