### ISSUE TITLE
Support setting of default domain

### ISSUE THREAD

**Issue by kelchm** [rawmind0/alpine-traefik#23]
Would it be possible to specify a default domain that would be utilized when the `traefik.domain` label is not present on a service? I see that Traefik seems to support this, but I'm not sure that it functions like I am expecting.

As an example, if I made `cluster-1.foo.com` the default domain for traefik globally, all I would need to do is set `traefik.port` and `traefik.enable` within the services I would like to expose.

**Comment by rawmind0** [comment]
Hi @kelchm 

In last alpine-traefik release, 1.4.0-3 traefik built in rancher integration is supported, metadata and api. Also, community-catalog is already updated. Now 3 rancher integration are available, metadata, api ( traefik built in) or external (rancher-traefik). 

Take into account that labels are different with traefik built in integration, https://docs.traefik.io/configuration/backends/rancher/#labels-overriding-default-behaviour
Metadata with longpoll is the prefered integration, it’s working so good. 

If you use traefik built in integration, you could set default domain. :)

Best regards...

**Comment by rawmind0** [comment]
Closing...Please reopen if you have any problem...
