### ISSUE TITLE
How to configure InsecureSkipVerify=true for https node app with self signed cert

### ISSUE THREAD

**Issue by chrisfelix82** [rawmind0/alpine-traefik#27]
I have a node.js server that deals with authentication and thus needs traffic sent to it over https.  It has to have a self signed cert, as it has a private ip and is only accessible behind the proxy anyway.  I wanted to use the setting InsecureSkipVerify = true.  Is there an environment variable for that? or how would I do this?

**Comment by rawmind0** [comment]
Hi @chrisfelix82 ,

added TRAEFIK_INSECURE_SKIP env variable to set InsecureSkipVerify params...
https://github.com/rawmind0/alpine-traefik/commit/b86c57e249de06455657f404204d3cb0403c3f4b

alpine-traefik:1.2.3-1

**Comment by chrisfelix82** [comment]
Great!  Thanks

**Comment by darinabird** [comment]
> Hi @chrisfelix82 ,
> 
> added TRAEFIK_INSECURE_SKIP env variable to set InsecureSkipVerify params...
> [b86c57e](https://github.com/rawmind0/alpine-traefik/commit/b86c57e249de06455657f404204d3cb0403c3f4b)
> 
> alpine-traefik:1.2.3-1
> 
> :)

Dear @rawmind0 could you please open your description of the resolved problem, as I faced the same problem and your solution might be useful for me too😇
