### ISSUE TITLE
not resolving rancher-metadata

### ISSUE THREAD

**Issue by alexinthesky** [rawmind0/alpine-traefik#3]
Hi,

i'm having an issue where this particular container is not resolving short name rancher-metadata but it does resolv rancher-metadata.rancher.internal

strange because I have this in resolv.conf :
search traefik.rancher.internal traefik.traefik.rancher.internal rancher.interna
l
nameserver 169.254.169.250

all my other containers do resolv the short name...

did you face anything similar?.

A

**Comment by rawmind0** [comment]
Hi,

this is an alpine linux issue. It doesn't support glibc and it  doesn't support search in /etc/resolv.conf. 

If you use fqdn, you wouldn't have any problem.

**Comment by alexinthesky** [comment]
Understood, but then no rules.toml is generated from metadata using current image... Do you have a workaround?

**Comment by alexinthesky** [comment]
use alpine:edge?

**Comment by rawmind0** [comment]
I don't understand you @alexinthesky ... 

I have the service running in several systems and rules.toml is generated without any problem... It's confd who generates rules.toml , looking for traefik labels at the rancher-metadata...
What is the issue??

As i said you before, search issue is from alpine...alpine:edge is alpine...:P

**Comment by alexinthesky** [comment]
I have nothing generated in the rules.toml ( totally empty ) . 

I guess it is because my alpine-traefik:1.0.1-1 (which derives from alpine-monit:0.5.18-5 which derives from rawmind/alpine-base:0.3.4-1, from docker.io/alpine:3.4 ) container cannot resolv rancher-metadata.

this search option seams to be fixed in the alpine:edge image : see https://github.com/rancher/rancher/issues/5041

**Comment by rawmind0** [comment]
I think your guess it's not ok.....

Are you using alpine-traefik alone???  As you could read in README.md, you need to run alpine-traefik, with rancher-traefik as a sidekick, to get integration with rancher-metadata.

'''
Rancher

If you are running it in rancher, you could run rancher-traefik as a sidekick to get dynamic configuration.

Example

See rancher-example, that run a traefik lb in all infrastructure servers and publish ${TRAEFIK_HTTP_PORT}, ${TRAEFIK_HTTPS_PORT} and ${TRAEFIK_ADMIN_PORT} throught them.
'''

**Comment by alexinthesky** [comment]
Yes I am using a stack from the official rancher catalog... I'll investigate more and come back to you!

**Comment by rawmind0** [comment]
I have the package already running in some systems...

Have you set the traefik labels at the services you want to publish?? Also, service healthchecks are required  in order to work.

Do you have any log  error or warning??
monit logs: /opt/moni/log
confd logs: /opt/tools/confd/log
Traefik logs: /opt/traefik/log

**Comment by alexinthesky** [comment]
hey
i created an account on my rancher for you :

achappaz.fr:8080
user : raul
password : your home town in lower case

I have some stacks with the correct labels, for ex www :
  labels:
    traefik.domain: deportubes.com
    traefik.port: '80'
    traefik.enable: stack

**Comment by rawmind0** [comment]
Your error is here....
![image](https://cloud.githubusercontent.com/assets/11555446/17243759/b0959158-557e-11e6-83b8-f1577cb627c4.png)

**Comment by rawmind0** [comment]
I set the correct label and take a look at your rules.toml :)

**Comment by rawmind0** [comment]
The error was reported at confd logs...It was fail looking for traefik.domain label in dru stack web service...

Please...remove the account that you created me....

**Comment by alexinthesky** [comment]
great! thanks a lot!

**Comment by rawmind0** [comment]
You are welcome...a star would be a nice present.... :P

**Comment by rawmind0** [comment]
This is an error from alpine 3.4, but it doesn't affect the traefik service.

**Comment by airtonix** [comment]
@rawmind0 From what I can learn from this ticket and its comments, is that there are in fact two scenarios where this container needs to be ran with the sidekick: metadata and external mode?

When I use your rancher catalog in mode: metadata there is no sidekick launched.

**Comment by rawmind0** [comment]
@airtonix, this container needs to be run as sidekick just with external traefik integration. Metadata and api are traefik builtin integrations. 

In catalog package you need to select external integration to run it as sidekick.
