### ISSUE TITLE
Traefik 1.3.0-rc1

### ISSUE THREAD

**Issue by dbsanfte** [rawmind0/alpine-traefik#33]
Hey guys. Thanks for maintaining this.

Traefik has an RC out for 1.3 which includes the X-Forwarded-Prefix header, something we really need as we're doing a lot of PathPrefixStrip stuff. Any ideas when there will be an alpine-traefik image for this RC?

Cheers

**Comment by jean-francois-labbe** [comment]
Traefik v1.3.0 is out now.

**Comment by rawmind0** [comment]
Already updated traefik to version 1.3.3....
