### ISSUE TITLE
Dose anybody care about the compression option?

### ISSUE THREAD

**Issue by sirius1024** [rawmind0/alpine-traefik#43]
Could your guys add compress options for trarfik on rancher?

**Comment by sirius1024** [comment]
I've already submit a pull request for this issue. Could you check it please? 
[https://github.com/rawmind0/alpine-traefik/pull/44](url)

**Comment by rawmind0** [comment]
Could you please take a look at change requested at you PR?? [#44](https://github.com/rawmind0/alpine-traefik/pull/44)

**Comment by rawmind0** [comment]
Merged PR #44.... Thanks @sirius1024...
