### ISSUE TITLE
Traefik turns a `302 Found` response into `200 OK` for HTTP2 clients with compression enabled

### ISSUE THREAD

**Issue by insekticid** [rawmind0/alpine-traefik#62]
rollback to version 1.4.0 or upgrade to 1.4.3 (not released yet)

https://github.com/containous/traefik/issues/2351

**Comment by insekticid** [comment]
upgrade to traefik 1.4.3 - https://github.com/containous/traefik/tree/v1.4.3

**Comment by rawmind0** [comment]
https://github.com/rawmind0/alpine-traefik/pull/63
