### ISSUE TITLE
Upgrade to 1.4.3 overwrites Key and Crt Files

### ISSUE THREAD

**Issue by Sebisnow** [rawmind0/alpine-traefik#65]
We just upgraded Traefik on our Rancher env from 1.3.6 to 1.4.3. In the Rancher upgrade dialog we answered the questions including the insertion of new certificate and key files, but Traefik 1.4.3 overwrote our certificates (or did not use them in the first place).

We adjusted the Traefik labels on our services to

Consequently we could not connect to our services via https without getting a Net Certificate Error. To resolve this issue we had to start a shell session in Traefik and overwrite the invalid key and cert file with the same one we entered in the Rancher questions in the first place. Restarted Traefik and all was well.

Nevertheless the Traefik should use the key and crt file entered in the Rancher Dialog.

P.S. We upgraded Traefik for three environments and had the same issue in all three of them.

**Comment by rawmind0** [comment]
What traefik integration are you using?? 
I'm afraid that key and crt file entered in the Rancher Dialog are working only with `external` integration that uses rancher-traefik. Not working with `api` neither `metadata`

**Comment by jri-sp** [comment]
Hi,
I'm facing the same issue, and I'm using `metadata` integration.
I changed the cert manually trough Rancher shell. 
Is there a better way to do if I want to continue using the rancher catalog ? 

It could be cool if this could work with all integration mechanism, do you think it's possible to do ? Is it hard ? (maybe I can PR something if it's not difficult)

Best Regards!

**Comment by rawmind0** [comment]
Solved at last image release, rawmind/alpine-traefik:1.4.4-3

**Comment by jri-sp** [comment]
Last release is working great for me ! Thanks @rawmind0
