### ISSUE TITLE
How to utilize constraints for multiple traefik deployments?

### ISSUE THREAD

**Issue by claflico** [rawmind0/alpine-traefik#66]
Am using rawmind/alpine-traefik:1.4.4-0 in Rancher 1.6.10 in metadata mode. Is there a way to utilize "constraints" or "rancher.constraints" as env variables so that I can run multiple traefik services and filter out what containers are seen by what traefik service?

The command line equivalent is: "--constraints=tag==my-stack"

**Comment by rawmind0** [comment]
Wasn't... But take a look to the last release...rawmind/alpine-traefik:1.4.4-1

 ;)

**Comment by rawmind0** [comment]
Upgraded community catalog, https://github.com/rancher/community-catalog/pull/685

**Comment by claflico** [comment]
Awesome...thanks.
