### ISSUE TITLE
Traefik 1.4.x makes service 503 when it upgraded

### ISSUE THREAD

**Issue by sirius1024** [rawmind0/alpine-traefik#67]
rancher integration: external
https: true
Https keys: ---begin--- ... ---end---
Https crt: ---begin--- ... ---end---
compression: true
refresh Interval: 10
cattle url: v1 or v2 both I've tried
cattle access key & secret key: I generated new Environment API Keys for traefik.

I added or upgraded service and it'll be Service Unavailable

**Comment by rawmind0** [comment]
Issue related to rancher-traefik, https://github.com/rawmind0/rancher-traefik/issues/42
Solved at rancher-traefik last release.
