### ISSUE TITLE
Update to version 1.5

### ISSUE THREAD

**Issue by anlek** [rawmind0/alpine-traefik#68]
First of all, thank you so much for making this work with Rancher. I've started using it as of yesterday and loved it.
However, I need the HTTP to HTTPS redirect working, and it seems to be in version 1.5. I was wondering if it's possible (or what is required) to upgrade this 1.5?

**Comment by justb81** [comment]
1.5 is still in rc state, so i suggest not to update, yet

**Comment by anlek** [comment]
Oh, I thought it was out. Sorry for the distraction.

Anyone in the future, you can see the current version number on the release page: https://github.com/containous/traefik/releases
