### ISSUE TITLE
How to send traefik logs to stdout?

### ISSUE THREAD

**Issue by peceka** [rawmind0/alpine-traefik#7]
Hi,

in my environment I use fluentd to gather logs from all containers and send them to logstash/elasticsearch. Would be really nice to catch traefik logs in the same way. Right now I need to mount host volume, attach file to fluentd and of course have to watch file with logrotate.
Adding ENV variable for:
`accessLogsFile = "/opt/traefik/log/access.log"`
to send them to stdout really helps.

Regards,
p.

**Comment by rawmind0** [comment]
Hi @peceka ,

I added env variables, to control log file, and access file. Both of them are already redirected to docker stdout.

- TRAEFIK_LOG_FILE="/opt/traefik/log/traefik.log"}		# Log file. Redirected to docker stdout.
- TRAEFIK_ACCESS_FILE="/opt/traefik/log/access.log"}	# Access file. Redirected to docker stdout.

You could access logs with docker logs <alpine-traefik> 

Best regards,

**Comment by johnrengelman** [comment]
I know this is closed, but is there a way to also ship the logs from other services in this container (like confd) to stdout?

**Comment by rawmind0** [comment]
Yes, for sure... to redirect whatever to stdout, you should link it to /proc/1/fd/1...

confd log file is located at /opt/tools/confd/log/confd.log :)

Best regards...
