### ISSUE TITLE
My label "traefik.domain" doesn't seem to be in effect.

### ISSUE THREAD

**Issue by PeterZhai00** [rawmind0/alpine-traefik#72]
Version 1.4.5-0 I used on Rancher 
 The default domain used  *.rancher.internal
 I don't know what's the reason

**Comment by rawmind0** [comment]
What Rancher integration are you using, `metadata`, `api` or `external`?? 

As you can read at traefik catalog package description, `traefik.domain` label just works with `external` rancher integration, that use https://github.com/rawmind0/rancher-traefik . `metadata` and `api` rancher integration use traefik labels https://docs.traefik.io/configuration/backends/rancher/#labels-overriding-default-behaviour

**Comment by PeterZhai00** [comment]
I use "metadata"
