### ISSUE TITLE
acme: Could not determine solvers

### ISSUE THREAD

**Issue by Hermsi1337** [rawmind0/alpine-traefik#74]
I'm currently facing the error stated in title when trying to issue a new certificate.

Is this related to the following issue?
https://github.com/containous/traefik/issues/1832

If yes, sorry for asking!

Regards,
Hermsi

PS: 
Is it possible to use own certificates per service using labels? 
I checked the rancher-traefik repository but did not find any related configuration-possibilities https://github.com/rawmind0/rancher-traefik

**Comment by ekeih** [comment]
Yes, it is related to containous/traefik#1832. You can find a manual workaround in containous/traefik/issues/2691.

**Comment by Hermsi1337** [comment]
Hey @rawmind0 

In traefik-repo the request is merged: https://github.com/containous/traefik/pull/2701#pullrequestreview-88834078

Are there any new configurations needed in your rancher-traefik-template?
For now, it is not possible to issue new certs. ):

**Comment by justb81** [comment]
not sure if it's going to be in 1.5.0-rc5 or 1.5.0 final - 1.5 brings many other changes as well, so a quick update of @rawmind0 package is appreciated but not really realistic :-(

**Comment by Hermsi1337** [comment]
Oh hey @justb81 

I just saw your workaround in the issue referenced by @ekeih 

1. used janeczku/rancher-letsencrypt:v0.5.0 to get the cert-files.
2. than i copied the .pem to a (persistent) folder in my traefik-service.
3. rename the .pem files to .crt and .key
4. insert the files to traefik.toml under [entryPoints.https.tls]

Do you also have a good idea for workarounding the whole thing in rancher-traefik?

**Comment by justb81** [comment]
@Hermsi1337 rancher-traefik can do this (nearly) automagically:

instead of step 4, just set TRAEFIK_ACME_ENABLE = false and set TRAEFIK_SSL_PATH to your persistent folder. check that your .crt and .key file have the same basename.

**Comment by Hermsi1337** [comment]
@justb81 Doing it that way it is only possible to use one certificate, isn't it?
I have multiple domains.. but In Traefik I can only provide one cert.

Or am I missing a point?

**Comment by rawmind0** [comment]
@Hermsi1337 , @justb81 is right. You could use multiple certs and keys with same basename, if you place them in the TRAEFIK_SSL_PATH folder. It's implemented in alpine-traefik image.

**Comment by Hermsi1337** [comment]
I'm a bit of a blockhead right now... how do I name the .crt and .key files?
Do they have to be named like the domain? e.g. "www.example.com.crt" and "www.example.com.key"?

Sorry for asking that much ...

**Comment by rawmind0** [comment]
It would be useful a descriptive file names, to know which file is which certificate/key. It's mandatory to have same basename on key and crt files.

**Comment by Hermsi1337** [comment]
And how does Traefik now, which Service/Frontend belongs to which certificate so the domain and it's and its content is served via https?

**Comment by rawmind0** [comment]
Due to you could specify file name, or the certificate/key content in traefik sni config, 
https://docs.traefik.io/user-guide/examples/#http-https-with-sni , i guess traefik reads certificates common name and match it with requested host.

**Comment by Hermsi1337** [comment]
Isn't the traefik.toml overwritten by your service?
https://github.com/rawmind0/rancher-traefik

So if i manually add the certificates the entries will be deleted next time the template is applies, won't they?

**Comment by rawmind0** [comment]
Traefik acme need to be disabled, TRAEFIK_ACME_ENABLE = false, and disable it in your services....traefik.acme = false

**Comment by Hermsi1337** [comment]
wow.. so many thanks for your explanations! (=

So it is basically not possible to use both: Let's Encrypt an custom certificates

I understand.

**Comment by Hermsi1337** [comment]
It's me again 🤣 (The last time for today.. I swear!)

Currently I have to restart the whole traefik-container in order to get the .toml updatet.
Is there a command or kind of service which can be used to update the .toml on a regular basis?

**Comment by justb81** [comment]
@rawmind0 are you working on the 1.5.0-rc5 implementation or do you need help?

**Comment by rawmind0** [comment]
I'm on it, i expect to have a release this afternoon or tomorrow..

Thanks @justb81 .. :)

**Comment by rawmind0** [comment]
Released...`rawmind0/alpine-traefik:1.5.0-rc5-1`...

Added support for http and dns acme challenge...Take a look to the README.md.. :)

**Comment by wiesendaniel** [comment]
Hey @rawmind0,

you might want to make the variable `TRAEFIK_ACME_CHALLENGE=""` a bit safer.
It needs to be `TRAEFIK_ACME_CHALLENGE=http`
`TRAEFIK_ACME_CHALLENGE="http"` doesn't work. For some reason it compares X"http" to Xhttp.

```
if [ "X${TRAEFIK_ACME_CHALLENGE}" == "Xdns" ]; then
```

I don't think you need the "X" when using quotes, but that I'm not sure about.

Thanks for the quick fix BTW.

**Comment by Hermsi1337** [comment]
@rawmind0 thank you so much for the quick fix!
Can you expect when the new image is released in rancher-catalog?

**Comment by rawmind0** [comment]
Probably today or tomorrow, once traefik v1.5.0 was released today.

**Comment by rawmind0** [comment]
Updated Rancher catalog package..Refactored and added new v1.5.0 features.. Feedback would be appreciated.. :)

https://github.com/rancher/community-catalog/pull/725

**Comment by binary64** [comment]
In docker-compose.yml, using `image: rawmind/alpine-traefik:1.5.4-1`, I got the "could not determine solvers" error, solved by adding `TRAEFIK_ACME_CHALLENGE: http`

**Comment by adv-ai-tech** [comment]
bAtSymIwbDOnvOl3W271lSef4HlrKiGTkyqLoHwba5U
