### ISSUE TITLE
SSL redirect

### ISSUE THREAD

**Issue by piotrgiedziun** [rawmind0/alpine-traefik#77]
Hi!

Would you consider adding support for _traefik.frontend.headers.SSLRedirect_?

**Comment by rawmind0** [comment]
Hi @piotrgiedziun,

it could be done, but it isn't here, moreover at rawmind0/rancher-traefik git repo. :)

Best regards...

**Comment by xuxogarcia** [comment]
Hi,
Along these lines, I am using the traefik catalog provided by Rancher and SSL redirection doesn't seem to be happening. Am I missing a label or something for the 'magic' to happen? I checked the rancher-traefik repo but didn't find anything there

**Comment by binary64** [comment]
This might be related: I'm trying to do TRAEFIK_HTTPS_ENABLE="only" but when I visit http, it's redirecting me to port 8443. Feels like we need another variable to tell Traefik which port we are using on the public WAN (in my case, 443).

**Comment by rawmind0** [comment]
Yep, variable is `TRAEFIK_HTTPS_PORT=8443	# https port` take a look at README.md file :)

**Comment by binary64** [comment]
Unless you mean the `#` symbol is part of the data payload, I think you misunderstand. Traefik is listening on port 8443 inside the container. But using docker, it is being 'exposed' as port 443 to the outside world (in docker this is `-p 443:8443/tcp`).

**Comment by rawmind0** [comment]
`#` just denotes a comment. 
Traefik is listening on port $TRAEFIK_HTTPS_PORT that by default is 8443. Try to overwrite variable and publish same port as exposed `-p 443:443/tcp -e TRAEFIK_HTTPS_PORT=443`

**Comment by binary64** [comment]
Oooh, sorry. I thought I read somewhere it wouldn't work due to being non-root process. Thank you, it's working.
