### ISSUE TITLE
Adjusting the request timeout values

### ISSUE THREAD

**Issue by trauts2** [rawmind0/alpine-traefik#78]
This PR describes a feature we would like to use:
https://github.com/containous/traefik/pull/1873

We have one admin task which takes several minutes to complete, and traefik is timing out.  Is it possible to access this configuration without an enhancement to alpine-traefik?

Thanks!

Stu

**Comment by trauts2** [comment]
Is there a workaround for this?  We're getting gateway timeouts fairly frequently, I'd like to know of the correct way to increase the timeout value

**Comment by rawmind0** [comment]
@trauts2 , added timeouts env variables to control responding and forwarding timeouts at deployment time.  Take a look at README.md file
https://docs.traefik.io/configuration/commons/#timeouts 

Included at release `rawmind/alpine-traefik:1.5.4-1`

**Comment by trauts2** [comment]
Thanks!

How can I update to this version in my Rancher 1.14 instance?  I see the
previous version but not this one.

https://screencast.com/t/pNxyKwKOd7og

**Comment by trauts2** [comment]
I just tested this, and was able to set each of these timeout values.  In my test I set them all to 180seconds, then issued a request that would take about that long.  I received the timeout at 60 seconds exactly.  Is it possible these values aren't making their way to traefik correctly?
