### ISSUE TITLE
set monit check-port to first defined entrypoint

### ISSUE THREAD

**Issue by justb81** [rawmind0/alpine-traefik#81]
Monit watches hardcoded for port 8000. if you deactivate the admin entrypoint, it fails and restarts traefik.

Suggestions: Set monit to watch the port of the first defined entrypoint of traefik.

**Comment by rawmind0** [comment]
Solved issue at release 1.5.3-0. 

Monit now checks traefik process by pid, not port. 
https://github.com/rawmind0/alpine-traefik/commit/b944c8549eb88b5beb6bfeccd10dda87b32711cf
