### ISSUE TITLE
Allow setting of trustedIps, forwardedHeaders and proxyProtocol

### ISSUE THREAD

**Issue by justb81** [rawmind0/alpine-traefik#84]
To use Traefik behind a AWS ELB Proxy, we need to set `trustedIps` to allow forwarding the client-ip to the backend.

https://docs.traefik.io/configuration/entrypoints/#proxyprotocol

I suggest to allow setting the trustedIp array and enable proxyprotocol AND forwardedHeaders to all enabled entrypoints.

## Example Environment:
```
TRAEFIK_TRUSTEDIPS = 172.0.0.0/16,192.168.0.1
```
### results in:
```
[entryPoints.http.proxyProtocol]
      trustedIPs = ["172.0.0.0/16", "192.168.0.1"]
[entryPoints.http.forwardedHeaders]
      trustedIPs = ["172.0.0.0/16", "192.168.0.1"]
[…]
[entryPoints.https.proxyProtocol]
      trustedIPs = ["172.0.0.0/16", "192.168.0.1"]
[entryPoints.https.forwardedHeaders]
      trustedIPs = ["172.0.0.0/16", "192.168.0.1"]
```

**Comment by justb81** [comment]
@rawmind0 if this looks good for you, i will implement the PR

**Comment by rawmind0** [comment]
@justb81 , sure, more than happy to get a PR about it.
