### ISSUE TITLE
Admin auth doesn't work as documented

### ISSUE THREAD

**Issue by dizlexik** [rawmind0/alpine-traefik#88]
The README lists `TRAEFIK_ADMIN_BASIC_AUTH_USERS` and `TRAEFIK_ADMIN_DIGEST_AUTH_USERS` environment variables but I don't see them in the actual code. I noticed that `traefik.toml.sh` instead uses `TRAEFIK_ADMIN_AUTH_METHOD` and `TRAEFIK_ADMIN_AUTH_USERS`. I'm using basic auth right now by setting `TRAEFIK_ADMIN_AUTH_USERS` and it's working well, but either the README or config needs to be updated to be consistent. I don't know which, but if you end up updating the config to match the README then I'll need to know so I can modify my environment variables next time I upgrade alpine-traefik.

**Comment by rawmind0** [comment]
You are right, README.md was outdated. `TRAEFIK_ADMIN_AUTH_METHOD` and `TRAEFIK_ADMIN_AUTH_USERS` are the good variables to use. 

Thanks for the advize.
