### ISSUE TITLE
Update to v1.5.4

### ISSUE THREAD

**Issue by samvdb** [rawmind0/alpine-traefik#89]
Can we update to support https://github.com/containous/traefik/pull/2774?

This enabled permanent redirection in the frontend by setting `frontend.redirect.permanent=true`

**Comment by rawmind0** [comment]
Updated and released `rawmind/alpine-traefik:1.5.4-0`.

**Comment by robbatt** [comment]
is this already in the rancher traefik catalog? how would you configure this? I tried this on my application container, but still get 302 (browser caches disabled), same with curl -IvL
