### ISSUE TITLE
[Feature Request] Custom default 404 error page

### ISSUE THREAD

**Issue by claflico** [rawmind0/alpine-traefik#90]
I know that there's a lot of talk and work being done about custom error pages in Traefik and I see in the documentation that it looks like in version 1.6 there will be support for custom error pages using Rancher labels..... 

If I read the documentation correctly it is possible right now using the file backend to set custom labels but I can't quite understand how to use it....

Is there any way that you could something that would allow replacing the default 404 white screen with a custom page for now until 1.6 comes out?

**Comment by refusetofeel** [comment]
@claflico Traefik 1.6 has been pushed to a stable release, and has all available labels. 

[Traefik labels under rancher](https://github.com/containous/traefik/blob/master/docs/configuration/backends/rancher.md#labels-overriding-default-behavior)

[How an implementation would normally look like](https://github.com/containous/traefik/blob/master/docs/configuration/commons.md#custom-error-pages)

**Comment by claflico** [comment]
@refusetofeel yeah, unfortunately it's not working right. I have an issue open with containous and we are trying to troubleshoot it. I'll go ahead and close this.
