### ISSUE TITLE
Add traefik_rancher_domain

### ISSUE THREAD

**Issue by naerion89** [rawmind0/alpine-traefik#91]
Can you add the variable traefik_rancher_domain in rancher catalog form ?

**Comment by rawmind0** [comment]
Racher domain could be overridden by `traefik.domain` service label, https://docs.traefik.io/configuration/backends/rancher/#global-configuration

**Comment by naerion89** [comment]
i deploy traefik from rancher catalog.
The default domain  is rancher.internal. 

If i set traefik_domain label on any container behind traefik, the domain dont' change in UI (still rancher.internal).

I have to add traefik environnement variable traefik_rancher_domain to customize the domain name.

In fact, i need to step to get traefik working from rancher catalog : 

- add traefik from rancher catalog
- update traefik container and add environnement variable

**Comment by rawmind0** [comment]
Service label should be `traefik.domain` not `traefik_domain`..

**Comment by naerion89** [comment]
sorry,  i would say traefik.domain.

i did a new test with gitlab and traefik in rancher.
I set traefik.domain on gitlab container. It didn't work. In traefik UI, i saw gitlab.<stack_name>.rancher.internal.

**Comment by rawmind0** [comment]
Working fine with external integration, but it seems not working on api or metadata integration. I think it's an issue to be open at Traefik. 

By the moment, you could override host rule with service label `traefik.frontend.rule=Host:<SERVICE_FQDN>`
