### ISSUE TITLE
What are the exact conditions under which this works with Rancher?

### ISSUE THREAD

**Issue by rbhaddon** [rawmind0/alpine-traefik#96]
I've been messing with Traefik under Rancher 1.6.7 and 1.6.17, both on Docker CE 17.06.2, and I've never been able to see **anything** appear under Rancher on the Provider tab of the admin UI.
I've set all the labels in simple web stacks, I've enabled healthchecks...absolutely nothing.  I'm using Traefik with Rancher metadata.  I believe Traefik is triggering, because I see activity in the Traefik logs when services are coming up and down.  However, the Traefik logs **always** just say "Skipping same configuration for provider rancher", which I think means it failed to detect anything that would cause Traefik to update its rules.
I don't understand what I'm missing.

**Comment by rbhaddon** [comment]
It's working now.  I did two things:
1) I was using the version found in the Rancher community catalog, which pulls Docker image rawmind0/alpine-traefik:1.5.4-0, but now I'm running a modified version that uses Traefik 1.6.0-RC6 instead.
2) In my Rancher services, I was using label `traefik.enable=stack`, but now I'm using `traefik.enable=true`.
I intend to reverse these changes and see which one actually did the trick, or if both were needed.

The label `traefik.domain` does not seem to be respected, but I can achieve the same thing with `traefik.frontend.rule=Host:foo.abc.org`.

Thanks!

**Comment by rawmind0** [comment]
You were using wrong labels. These labels are only available for 'external' integration. It's explained at package README.md file. For 'metadata' and 'api' integration you should use thes labels, https://docs.traefik.io/configuration/backends/rancher/#labels-overriding-default-behaviour

**Comment by rawmind0** [comment]
Closing issue. Please, reopen it if its needed
